version: '3'

services:
  phpapp:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: php-elitery
    container_name: phpAlpineLaravelTest
    restart: unless-stopped
    networks:
      - laravelbackend
    volumes:
      - ../laravelapp/:/var/www/html/
    working_dir: /var/www/html

  nginxweb:
    image: nginx:alpine
    container_name: nginxAlpineLaravelTest
    restart: unless-stopped
    networks:
      - laravelbackend
    ports:
      - "8000:80"
    volumes:
      - ../laravelapp/:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mysql:5.7
    container_name: elitery-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    networks:
      - laravelbackend
    volumes:
      - mysqldata:/var/lib/mysql/

networks:
  laravelbackend:
    driver: bridge

volumes:
  mysqldata:
    driver: local