version: '3.7'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: php-elitery
    container_name: phpAlpineLaravelTest
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ../laravelapp:/var/www/app
    #entrypoint: php artisan serve --host=0.0.0.0

  db:
    image: mysql:5.7
    container_name: elitery-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - 3306:3306
    volumes:
      - ../mysql/:/docker-entrypoint-initdb.d