version: '3'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        phpvers: ${PHPVERS}
    restart: unless-stopped
    image: php-elitery
    container_name: phpAlpineLaravelTest
    working_dir: /var/www/
    volumes:
      - ../laravelapp:/var/www
    #entrypoint: php artisan serve --host=0.0.0.0

  db:
    image: mysql:latest
    container_name: elitery-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ../mysql/:/docker-entrypoint-initdb.d